credit<-read.csv(file.choose())
View(credit)
str(credit)
table(credit$checking_balance)
table(credit$savings_balance)
summary(credit$months_loan_duration)
summary(credit$amount)
table(credit$default)
set.seed(12345)
credit_rand<-credit[order(runif(1000)),]
summary(credit$amount)
summary(credit_rand$amount)
head(credit$amount)
head(credit_rand$amount)

credit_train<-credit_rand[1:900,]
View(credit_train)
credit_test<-credit_rand[901:1000,]
prop.table(table(credit_train$default))
prop.table(table(credit_test$default))
factor(credit_train$default)
library(randomForest)
credit_model<-randomForest(credit_train,credit_train$default,ntree=500)
credit_model
