volcanodust<-scan("http://robjhyndman.com/tsdldata/annual/dvi.dat", skip=1)
View(volcanodust)
volcanodustseries <- ts(volcanodust,start=c(1500))
plot.ts(volcanodustseries)
library(tseries)
ndiffs(volcanodustseries)
acf(volcanodustseries)
pacf(volcanodustseries)
auto.arima(volcanodustseries)
auto.arima(data,trace=TRUE,ic="bic",approximation = FALSE,stepwise = FALSE)
